world: &world
  table: demo_world
  count: 0
  fields:
    name:
      generator: Text
      params:
        nullable: false
        min_length: 1
        max_length: 30
    description:
      generator: Text
      params:
        nullable: false
        min_length: 0
        max_length: null

city: &city
  table: demo_city
  count: 0
  fields:
    world_id:
      generator: ForeignKey
      params:
        nullable: false
        target: world
        field: id
    name:
      generator: Text
      params:
        nullable: false
        min_length: 1
        max_length: 40

abode: &abode
  table: demo_abode
  count: 0
  fields:
    city_id:
      generator: ForeignKey
      params:
        nullable: false
        target: city
        field: id
    owner_id:
      generator: ForeignKey
      params:
        nullable: true
        target: citizen
        field: id
        unique: true
    type:
      generator: Choices
      params:
        nullable: false
        choices: ['SH', 'H', 'SB', 'B']

citizen: &citizen
  table: demo_citizen
  count: 0
  fields:
    abode_id:
      generator: ForeignKey
      params:
        nullable: false
        target: abode
        field: id
    first_name:
      generator: Text
      params:
        nullable: false
        min_length: 1
        max_length: 20
    middle_name:
      generator: Text
      params:
        nullable: false
        min_length: 0
        max_length: 20
    last_name:
      generator: Text
      params:
        nullable: false
        min_length: 1
        max_length: 20
    birth:
      generator: Date
      params:
        nullable: false
    gender:
      generator: Choices
      params:
        nullable: false
        choices: ['M', 'F']

hobby: &hobby
  table: demo_hobby
  count: 0
  fields:
    name:
      generator: Text
      params:
        nullable: false
        min_length: 1
        max_length: 40

hobby_citizens_through_table: &hobby_citizens_through_table
  table: demo_hobby_citizens
  count: 0
  fields:
    hobby_id:
      generator: ForeignKey
      params:
        nullable: false
        target: hobby
        field: id
    citizen_id:
      generator: ForeignKey
      params:
        nullable: false
        target: citizen
        field: id
